### ISSUE TITLE
Allow different encoding of output

### ISSUE THREAD

**Issue by yeya** [lucagrulla/node-tail#48]
I am trying to tail a UTF-16le encoded file.
I can't figure how to pass this argument.
I tried by `fsWatchOptions` but I think it's just the filename encoding, not the file content.

**Comment by lucagrulla** [comment]
Yes currently the only supported encoding is UTF-8. 

The change by itself is trivial(pass an extra option defaulted to utf-8 and use it in the readBlock method) but the testing needs to be exhaustive, because the moment any encoding is allowed there's then the need to be sure that not funny things happening along the way.

A PR with very good testing coverage it's encouraged :-)

**Comment by lucagrulla** [comment]
1.2.2 should fix the problem
